theme: jekyll-theme-slate
title: "Faouzi Hakimi"
description: "Bienvenu sur ma page ! Vous y trouverez des informations concernant mon travail, mes projets personnels ainsi que quelques articles de blog"
